Update
deltaray/cloudperm pull request #11
Opened 2021-04-15 14:52 UTC by cybath

In this update we bring Cloudperm onto Python3. At this point in time Cloudperm should continue to work on Python2, however for future development (the next update) Python2 will no longer be supported.

2021-04-21 18:48 UTC, deltaray requested changes
Please remove the data files (TSV and JSON) that were accidentally submitted as part of this.

2021-04-21 18:48 UTC, deltaray commented on listFiles
> +                path = path.replace("▶", ">")
This will always be an issue with unescaped output.  WIth a filesystem, we can count on certain characters like / and null not being used in paths, but with Google drive probably only null would work.

2021-04-21 18:48 UTC, deltaray commented on listFiles.csv
> +1NfsF3OZW7fNo7ttT7j0pF_vbheQpF5Hr,Cloudperm  >
Be careful about submitting files into the repo that you don't intend to. You probably need to add some exclude lines to your git configuration for certain files.

2021-04-22 15:20 UTC, cybath commented
Will start new pull request without those files

2021-04-22 15:20 UTC, closed without merging